name: Test CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run sample command
        run: echo "🚀 Hello from GitHub Actions!"

